language: node_js
install:
  - npm install -g codecov
  - npm install
node_js:
  - 'node'
services:
  - postgresql
before_script:
  - npm install -g mocha
  - npm install -g nyc
  - npm install -g sequelize-cli
  - psql -c 'create database recipe_test;' -U postgres
script:
  - npm run test:server
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

after_success: 
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
  - ./node_modules/.bin/coveralls --verbose < coverage/lcov.info
